<a href="https://colab.research.google.com/github/fardsnog2/ML_vvsu/blob/main/ml_oiad.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pymorphy2
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer
import pymorphy2
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
import nltk
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,multilabel_confusion_matrix,classification_report,f1_score
nltk.download('stopwords')
nltk.download('punkt')

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.5/55.5 kB 936.9 kB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.2/8.2 MB 27.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13706 sha256=2ba808d017cf713927409a68289079b189c2b5391f8d5f2cbf1b0f051fc30482
  Stored in directory: /root/.cache/pip/wheels/fc/ab/d4/5da2067ac95b36618c629a5f93f809425700506f72c9732fac
Successfully built docopt


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [2]:
df = pd.read_excel('/content/comments_ml.xlsx')[['text','Marker']]
df

text Marker
0                                 Хороший преподователь      P
1                                 С наступающим вас! :)     NT
2                      Сложная и непонятная дисциплина       N
3                                        Учитель мечты       P
4                                Отличный преподаватель      P
...                                                 ...    ...
6549  Преподаватель не ведёт разболовку. В начале уч...      N
6550  Не проявляет никакого уважения к студентам, пр...      N
6551                                          все супер      P
6552                        Очень хороший преподаватель      P
6553                                                  .     NT

[6554 rows x 2 columns]

In [3]:
y = df['Marker'].apply(lambda x: x.upper())
X = df['text']
X

0                                   Хороший преподователь
1                                   С наступающим вас! :)
2                        Сложная и непонятная дисциплина 
3                                          Учитель мечты 
4                                  Отличный преподаватель
                              ...                        
6549    Преподаватель не ведёт разболовку. В начале уч...
6550    Не проявляет никакого уважения к студентам, пр...
6551                                            все супер
6552                          Очень хороший преподаватель
6553                                                    .
Name: text, Length: 6554, dtype: object

In [4]:
import re
def preproc_text(text):
    norm_text=[]
    morph=pymorphy2.MorphAnalyzer()
    for s in text:
      try:
        s1 = re.sub(r'[^\w\s]+|[\d]+', r'',s).strip()
        s1 = s1.lower()
        s1 = word_tokenize(s1)
        words=[]
        for i in s1:
            pv = morph.parse(i)
            words.append(str(pv[0].normal_form))
        sentence=' '.join(words)
        norm_text.append(sentence)
      except Exception as e:
        norm_text.append('')
    return norm_text

In [5]:
text_token = preproc_text(X)



In [7]:
tfidf_vectorizer = TfidfVectorizer(max_features=500,stop_words=stopwords.words('russian'))
X_desc = tfidf_vectorizer.fit_transform(text_token)
text_cv = pd.DataFrame(X_desc.toarray(),columns=tfidf_vectorizer.get_feature_names_out())
text_cv

best  абсолютно  активный  актуальный  александрович  алексеевич  \
0      0.0        0.0       0.0         0.0            0.0         0.0   
1      0.0        0.0       0.0         0.0            0.0         0.0   
2      0.0        0.0       0.0         0.0            0.0         0.0   
3      0.0        0.0       0.0         0.0            0.0         0.0   
4      0.0        0.0       0.0         0.0            0.0         0.0   
...    ...        ...       ...         ...            ...         ...   
6549   0.0        0.0       0.0         0.0            0.0         0.0   
6550   0.0        0.0       0.0         0.0            0.0         0.0   
6551   0.0        0.0       0.0         0.0            0.0         0.0   
6552   0.0        0.0       0.0         0.0            0.0         0.0   
6553   0.0        0.0       0.0         0.0            0.0         0.0   

      анатолиевич  английский  андреевич  анна  ...  школа  экзамен  \
0             0.0         0.0        0.0   0.0  ...    0.0      0.0   
1             0.0         0.0        0.0   0.0  ...    0.0      0.0   
2             0.0         0.0        0.0   0.0  ...    0.0      0.0   
3             0.0         0.0        0.0   0.0  ...    0.0      0.0   
4             0.0         0.0        0.0   0.0  ...    0.0      0.0   
...           ...         ...        ...   ...  ...    ...      ...   
6549          0.0         0.0        0.0   0.0  ...    0.0      0.0   
6550          0.0         0.0        0.0   0.0  ...    0.0      0.0   
6551          0.0         0.0        0.0   0.0  ...    0.0      0.0   
6552          0.0         0.0        0.0   0.0  ...    0.0      0.0   
6553          0.0         0.0        0.0   0.0  ...    0.0      0.0   

      электронный  это  юмор  юриевич  являться  язык  ясно  ясный  
0             0.0  0.0   0.0      0.0       0.0   0.0   0.0    0.0  
1             0.0  0.0   0.0      0.0       0.0   0.0   0.0    0.0  
2             0.0  0.0   0.0      0.0       0.0   0.0   0.0    0.0  
3             0.0  0.0   0.0      0.0       0.0   0.0   0.0    0.0  
4             0.0  0.0   0.0      0.0       0.0   0.0   0.0    0.0  
...           ...  ...   ...      ...       ...   ...   ...    ...  
6549          0.0  0.0   0.0      0.0       0.0   0.0   0.0    0.0  
6550          0.0  0.0   0.0      0.0       0.0   0.0   0.0    0.0  
6551          0.0  0.0   0.0      0.0       0.0   0.0   0.0    0.0  
6552          0.0  0.0   0.0      0.0       0.0   0.0   0.0    0.0  
6553          0.0  0.0   0.0      0.0       0.0   0.0   0.0    0.0  

[6554 rows x 500 columns]

In [8]:
label = LabelEncoder()
y_label = label.fit_transform(y)

In [9]:
text_cv['Y']=y_label
text_cv

best  абсолютно  активный  актуальный  александрович  алексеевич  \
0      0.0        0.0       0.0         0.0            0.0         0.0   
1      0.0        0.0       0.0         0.0            0.0         0.0   
2      0.0        0.0       0.0         0.0            0.0         0.0   
3      0.0        0.0       0.0         0.0            0.0         0.0   
4      0.0        0.0       0.0         0.0            0.0         0.0   
...    ...        ...       ...         ...            ...         ...   
6549   0.0        0.0       0.0         0.0            0.0         0.0   
6550   0.0        0.0       0.0         0.0            0.0         0.0   
6551   0.0        0.0       0.0         0.0            0.0         0.0   
6552   0.0        0.0       0.0         0.0            0.0         0.0   
6553   0.0        0.0       0.0         0.0            0.0         0.0   

      анатолиевич  английский  андреевич  анна  ...  экзамен  электронный  \
0             0.0         0.0        0.0   0.0  ...      0.0          0.0   
1             0.0         0.0        0.0   0.0  ...      0.0          0.0   
2             0.0         0.0        0.0   0.0  ...      0.0          0.0   
3             0.0         0.0        0.0   0.0  ...      0.0          0.0   
4             0.0         0.0        0.0   0.0  ...      0.0          0.0   
...           ...         ...        ...   ...  ...      ...          ...   
6549          0.0         0.0        0.0   0.0  ...      0.0          0.0   
6550          0.0         0.0        0.0   0.0  ...      0.0          0.0   
6551          0.0         0.0        0.0   0.0  ...      0.0          0.0   
6552          0.0         0.0        0.0   0.0  ...      0.0          0.0   
6553          0.0         0.0        0.0   0.0  ...      0.0          0.0   

      это  юмор  юриевич  являться  язык  ясно  ясный  Y  
0     0.0   0.0      0.0       0.0   0.0   0.0    0.0  2  
1     0.0   0.0      0.0       0.0   0.0   0.0    0.0  1  
2     0.0   0.0      0.0       0.0   0.0   0.0    0.0  0  
3     0.0   0.0      0.0       0.0   0.0   0.0    0.0  2  
4     0.0   0.0      0.0       0.0   0.0   0.0    0.0  2  
...   ...   ...      ...       ...   ...   ...    ... ..  
6549  0.0   0.0      0.0       0.0   0.0   0.0    0.0  0  
6550  0.0   0.0      0.0       0.0   0.0   0.0    0.0  0  
6551  0.0   0.0      0.0       0.0   0.0   0.0    0.0  2  
6552  0.0   0.0      0.0       0.0   0.0   0.0    0.0  2  
6553  0.0   0.0      0.0       0.0   0.0   0.0    0.0  1  

[6554 rows x 501 columns]

In [10]:
# 2 - P
# 1 - NT
# 0 - N

In [11]:
X_train, X_test, y_train, y_test = train_test_split(text_cv.drop(columns=['Y']), text_cv['Y'], test_size=0.2, random_state=42)

In [12]:
#model = RandomForestClassifier(n_estimators = 1000,max_depth=100)

model = RandomForestClassifier(n_estimators = 5000,max_depth=100)
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
accuracy_score(y_test,y_pred)

0.8535469107551488

In [13]:
confusion_matrix(y_test,y_pred)

array([[ 82,  14,  65],
       [ 10, 150,  30],
       [ 12,  61, 887]])

In [14]:
multilabel_confusion_matrix(y_test,y_pred)

array([[[1128,   22],
        [  79,   82]],

       [[1046,   75],
        [  40,  150]],

       [[ 256,   95],
        [  73,  887]]])

In [15]:
import warnings
#для удаления комментариев об ошибке в терминале
warnings.filterwarnings('ignore')
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.79      0.51      0.62       161
           1       0.67      0.79      0.72       190
           2       0.90      0.92      0.91       960

    accuracy                           0.85      1311
   macro avg       0.79      0.74      0.75      1311
weighted avg       0.85      0.85      0.85      1311



In [16]:
set(y)

{'N', 'NT', 'P'}

In [17]:
f1_score(y_test,y_pred, average='micro')

0.8535469107551488

In [18]:
model1 = SVC(gamma='auto')
model1.fit(X_train,y_train)
y_pred_1 = model1.predict(X_test)
f1_score(y_test,y_pred_1, average='micro')

0.7322654462242562

In [19]:
for i in range(1,150):
  model2 = KNeighborsClassifier(n_neighbors=i) #LogisticRegression
  model2.fit(X_train,y_train)
  y_pred_2=  model2.predict(X_test)
  print(i,' - ',f1_score(y_test,y_pred_2, average='micro'))

1  -  0.7315026697177726
2  -  0.6788710907704043
3  -  0.7200610221205186
4  -  0.6781083142639207
5  -  0.6857360793287567
6  -  0.6628527841342486
7  -  0.6598016781083142
8  -  0.6430205949656751
9  -  0.6483600305110603
10  -  0.6605644546147978
11  -  0.6895499618611747
12  -  0.6887871853546911
13  -  0.7467581998474448
14  -  0.7566742944317315
15  -  0.7543859649122807
16  -  0.7269260106788712
17  -  0.7162471395881007
18  -  0.6979405034324943
19  -  0.7147215865751335
20  -  0.6735316552250191
21  -  0.6681922196796338
22  -  0.6437833714721587
23  -  0.6483600305110603
24  -  0.6445461479786423
25  -  0.665903890160183
26  -  0.6491228070175439
27  -  0.669717772692601
28  -  0.6521739130434783
29  -  0.6598016781083142
30  -  0.6346300533943554
31  -  0.6384439359267735
32  -  0.6285278413424866
33  -  0.623951182303585
34  -  0.6071700991609459
35  -  0.6193745232646835
36  -  0.6041189931350115
37  -  0.6033562166285278
38  -  0.5942028985507246
39  -  0.596491228070175

In [21]:
model4 = LogisticRegression()
model4.fit(X_train, y_train)
y_pred_4 = model4.predict(X_test)
f1_score(y_test,y_pred_4, average='micro')

0.8619374523264683

In [22]:
from sklearn.model_selection import cross_val_score

In [23]:
scores = cross_val_score(model, text_cv.drop(columns=['Y']), text_cv['Y'], cv=5,scoring = 'f1_micro')

In [24]:
scores

array([0.8085431 , 0.80778032, 0.86880244, 0.81998474, 0.79007634])

In [25]:
scores.mean()

0.8190373876942605

In [26]:
scores = cross_val_score(model4, text_cv.drop(columns=['Y']), text_cv['Y'], cv=5,scoring = 'f1_micro')

In [27]:
scores.mean()

0.8408564058669741

In [30]:
!pip install Faker
from faker import Faker

In [31]:
fake = Faker('ru_RU')

In [35]:
fake.first_name()

'Родион'

In [37]:
text_token

['хороший преподователь',
 'с наступать вы',
 'сложный и непонятный дисциплина',
 'учитель мечта',
 'отличный преподаватель',
 'отличный работа',
 'отличный работа',
 'я всё нравиться анна сергеевич всегда помогать и хорошо объяснять материал',
 'учитель очень ответственный доброжелательный и очень хороший',
 'учитель очень ответственный доброжелательный и очень хороший',
 'учитель очень ответственный доброжелательный и очень хороший',
 'учитель очень ответственный доброжелательный и очень хороший',
 'учитель очень ответственный доброжелательный и очень хороший',
 'учитель очень ответственный доброжелательный и очень хороший',
 'учитель очень ответственный доброжелательный и очень хороший',
 'учитель очень ответственный доброжелательный и очень хороший',
 'учитель очень ответственный доброжелательный и очень хороший',
 'учитель очень ответственный доброжелательный и очень хороший',
 'учитель очень ответственный доброжелательный и очень хороший',
 'учитель очень ответственный доброжелат

In [50]:
!pip install natasha
from natasha import (
    Segmenter,
    MorphVocab,
    PER,
    NamesExtractor,
    NewsNERTagger,
    NewsEmbedding,
    Doc
)

In [90]:

emb = NewsEmbedding()
segmenter = Segmenter()
morph_vocab = MorphVocab()
ner_tagger = NewsNERTagger(emb)
names_extractor = NamesExtractor(morph_vocab)
new_X = []
for i in X:
  try:
    text_izm = i
    doc = Doc(i)
    doc.segment(segmenter)
    doc.tag_ner(ner_tagger)
    for span in doc.spans:
        span.normalize(morph_vocab)
    {_.text: _.normal for _ in doc.spans}

    for span in doc.spans:
        if span.type == PER:
            span.extract_fact(names_extractor)
    for _ in doc.spans:
      if _.type == PER:
        text_izm = text_izm.replace(_.normal,'')
    new_X.append(text_izm)
  except TypeError:
      new_X.append('')

In [91]:
len(new_X)

6554

In [92]:
text_token_new = preproc_text(new_X)

In [96]:
tfidf_vectorizer = TfidfVectorizer(max_features=1000,stop_words=stopwords.words('russian'),max_df=0.9)
X_desc = tfidf_vectorizer.fit_transform(text_token_new)
text_cv_new = pd.DataFrame(X_desc.toarray(),columns=tfidf_vectorizer.get_feature_names_out())
text_cv_new

best  python  teacher  the  абонемент  абсолютно  автомат  адекватно  \
0      0.0     0.0      0.0  0.0        0.0        0.0      0.0        0.0   
1      0.0     0.0      0.0  0.0        0.0        0.0      0.0        0.0   
2      0.0     0.0      0.0  0.0        0.0        0.0      0.0        0.0   
3      0.0     0.0      0.0  0.0        0.0        0.0      0.0        0.0   
4      0.0     0.0      0.0  0.0        0.0        0.0      0.0        0.0   
...    ...     ...      ...  ...        ...        ...      ...        ...   
6549   0.0     0.0      0.0  0.0        0.0        0.0      0.0        0.0   
6550   0.0     0.0      0.0  0.0        0.0        0.0      0.0        0.0   
6551   0.0     0.0      0.0  0.0        0.0        0.0      0.0        0.0   
6552   0.0     0.0      0.0  0.0        0.0        0.0      0.0        0.0   
6553   0.0     0.0      0.0  0.0        0.0        0.0      0.0        0.0   

      адекватный  адрес  ...  это  юмор  юриевич  являться  явно  язык  яркий  \
0            0.0    0.0  ...  0.0   0.0      0.0       0.0   0.0   0.0    0.0   
1            0.0    0.0  ...  0.0   0.0      0.0       0.0   0.0   0.0    0.0   
2            0.0    0.0  ...  0.0   0.0      0.0       0.0   0.0   0.0    0.0   
3            0.0    0.0  ...  0.0   0.0      0.0       0.0   0.0   0.0    0.0   
4            0.0    0.0  ...  0.0   0.0      0.0       0.0   0.0   0.0    0.0   
...          ...    ...  ...  ...   ...      ...       ...   ...   ...    ...   
6549         0.0    0.0  ...  0.0   0.0      0.0       0.0   0.0   0.0    0.0   
6550         0.0    0.0  ...  0.0   0.0      0.0       0.0   0.0   0.0    0.0   
6551         0.0    0.0  ...  0.0   0.0      0.0       0.0   0.0   0.0    0.0   
6552         0.0    0.0  ...  0.0   0.0      0.0       0.0   0.0   0.0    0.0   
6553         0.0    0.0  ...  0.0   0.0      0.0       0.0   0.0   0.0    0.0   

      ясно  ясность  ясный  
0      0.0      0.0    0.0  
1      0.0      0.0    0.0  
2      0.0      0.0    0.0  
3      0.0      0.0    0.0  
4      0.0      0.0    0.0  
...    ...      ...    ...  
6549   0.0      0.0    0.0  
6550   0.0      0.0    0.0  
6551   0.0      0.0    0.0  
6552   0.0      0.0    0.0  
6553   0.0      0.0    0.0  

[6554 rows x 1000 columns]

In [97]:
text_cv_new['Y']=y_label
text_cv_new

best  python  teacher  the  абонемент  абсолютно  автомат  адекватно  \
0      0.0     0.0      0.0  0.0        0.0        0.0      0.0        0.0   
1      0.0     0.0      0.0  0.0        0.0        0.0      0.0        0.0   
2      0.0     0.0      0.0  0.0        0.0        0.0      0.0        0.0   
3      0.0     0.0      0.0  0.0        0.0        0.0      0.0        0.0   
4      0.0     0.0      0.0  0.0        0.0        0.0      0.0        0.0   
...    ...     ...      ...  ...        ...        ...      ...        ...   
6549   0.0     0.0      0.0  0.0        0.0        0.0      0.0        0.0   
6550   0.0     0.0      0.0  0.0        0.0        0.0      0.0        0.0   
6551   0.0     0.0      0.0  0.0        0.0        0.0      0.0        0.0   
6552   0.0     0.0      0.0  0.0        0.0        0.0      0.0        0.0   
6553   0.0     0.0      0.0  0.0        0.0        0.0      0.0        0.0   

      адекватный  адрес  ...  юмор  юриевич  являться  явно  язык  яркий  \
0            0.0    0.0  ...   0.0      0.0       0.0   0.0   0.0    0.0   
1            0.0    0.0  ...   0.0      0.0       0.0   0.0   0.0    0.0   
2            0.0    0.0  ...   0.0      0.0       0.0   0.0   0.0    0.0   
3            0.0    0.0  ...   0.0      0.0       0.0   0.0   0.0    0.0   
4            0.0    0.0  ...   0.0      0.0       0.0   0.0   0.0    0.0   
...          ...    ...  ...   ...      ...       ...   ...   ...    ...   
6549         0.0    0.0  ...   0.0      0.0       0.0   0.0   0.0    0.0   
6550         0.0    0.0  ...   0.0      0.0       0.0   0.0   0.0    0.0   
6551         0.0    0.0  ...   0.0      0.0       0.0   0.0   0.0    0.0   
6552         0.0    0.0  ...   0.0      0.0       0.0   0.0   0.0    0.0   
6553         0.0    0.0  ...   0.0      0.0       0.0   0.0   0.0    0.0   

      ясно  ясность  ясный  Y  
0      0.0      0.0    0.0  2  
1      0.0      0.0    0.0  1  
2      0.0      0.0    0.0  0  
3      0.0      0.0    0.0  2  
4      0.0      0.0    0.0  2  
...    ...      ...    ... ..  
6549   0.0      0.0    0.0  0  
6550   0.0      0.0    0.0  0  
6551   0.0      0.0    0.0  2  
6552   0.0      0.0    0.0  2  
6553   0.0      0.0    0.0  1  

[6554 rows x 1001 columns]

In [98]:
scores = cross_val_score(model4, text_cv_new.drop(columns=['Y']), text_cv_new['Y'], cv=5,scoring = 'f1_micro')
scores,scores.mean()

(array([0.83066362, 0.84591915, 0.88176964, 0.83218917, 0.81603053]),
 0.8413144211341498)

In [99]:
scores = cross_val_score(model, text_cv_new.drop(columns=['Y']), text_cv_new['Y'], cv=5,scoring = 'f1_micro')
scores,scores.mean()

(array([0.81235698, 0.80015256, 0.86575133, 0.81235698, 0.79389313]),
 0.8169021957482488)

In [101]:
X_train_1, X_test_1, y_train_1, y_test_1 = train_test_split(text_cv_new.drop(columns=['Y']), text_cv_new['Y'], test_size=0.2, random_state=42)

In [102]:
test_model = RandomForestClassifier(n_estimators=10000,max_depth=150)
test_model.fit(X_train_1,y_train_1)
y_pred_test = test_model.predict(X_test_1)
f1_score(y_test_1,y_pred_test, average='micro')

0.8543096872616324

In [ ]:
from sklearn.model_selection import GridSearchCV
import numpy as np
param_grid = [
    {'penalty' : ['l1', 'l2', 'elasticnet', 'none'],
    'C' : np.logspace(-10, 10, 20),
    'solver' : ['lbfgs','newton-cg','liblinear','sag','saga'],
    'max_iter' : [100, 1000,2500, 5000]
    }
]
for pen in ['l1', 'l2', 'elasticnet', 'none']:
  for c in np.logspace(-10, 10, 20):
    for solv in ['lbfgs','newton-cg','liblinear','sag','saga']:
      for ite in [100, 1000,2500, 5000]:
        try:
          model4 = LogisticRegression(penalty=pen,C=c,solver=solv,max_iter=ite)
          scores = cross_val_score(model4, text_cv_new.drop(columns=['Y']), text_cv_new['Y'], cv=5,scoring = 'f1_micro')
          print(pen,' - ',c,' - ',solv,' - ',ite)
          print(scores,scores.mean())
        except ValueError:
          pass

l1  -  1e-10  -  liblinear  -  100
[0.12356979 0.12356979 0.12356979 0.12433257 0.12366412] 0.12374121496905224
l1  -  1e-10  -  liblinear  -  1000
[0.12356979 0.12356979 0.12356979 0.12433257 0.12366412] 0.12374121496905224
l1  -  1e-10  -  liblinear  -  2500
[0.12356979 0.12356979 0.12356979 0.12433257 0.12366412] 0.12374121496905224
l1  -  1e-10  -  liblinear  -  5000
[0.12356979 0.12356979 0.12356979 0.12433257 0.12366412] 0.12374121496905224
l1  -  1e-10  -  saga  -  100
[0.72158658 0.72158658 0.72158658 0.72158658 0.72137405] 0.721544069267094
l1  -  1e-10  -  saga  -  1000
[0.72158658 0.72158658 0.72158658 0.72158658 0.72137405] 0.721544069267094
l1  -  1e-10  -  saga  -  2500
[0.72158658 0.72158658 0.15484363 0.72158658 0.72137405] 0.6081954804036311
l1  -  1e-10  -  saga  -  5000
[0.72158658 0.72158658 0.72158658 0.72158658 0.72137405] 0.721544069267094
l1  -  1.1288378916846883e-09  -  liblinear  -  100
[0.12356979 0.12356979 0.12356979 0.12433257 0.12366412] 0.12374121496905